#!/bin/sh -e
update-rc.d gluu-engine defaults > /dev/null
service gluu-engine start
#mkdir -p /var/lib/gluu-cluster
#mkdir -p /var/log/gluu
#chmod 644 /var/log/gluu/*
install -d 755 /var/lib/gluu-cluster
install -d 755 /var/log/gluu
